"""Verify FSBL certificates generated by the RA8M1 provisioning flow."""
import struct
import hashlib
import sys

if sys.platform == 'win32':
    # Ensure UTF-8 output on Windows terminals
    sys.stdout.reconfigure(encoding='utf-8')

# Base path to the flow output folder containing key_cert_v1.bin and code_cert_v1.bin.
# Can be overridden via first command-line argument:
#   python verify_flow_certs.py C:\path\to\flow_folder
if len(sys.argv) > 1:
    base_path = sys.argv[1]
else:
    # Placeholder example path – replace with your actual flow folder when using this script.
    base_path = r'C:\Path\To\provisioning_tool\output\flow_YYYYMMDD_HHMMSS'

print("="*80)
print("VERIFYING CERTIFICATES IN FLOW")
print("="*80)
print()

# Key Certificate
print("KEY CERTIFICATE v1:")
print("-"*80)
key_cert = open(f'{base_path}\\key_cert_v1.bin', 'rb').read()
print(f"Size: {len(key_cert)} bytes")

magic = key_cert[0:4]
print(f"Magic: {magic.hex()} = {''.join(chr(b) for b in magic if 32 <= b < 127)}")
print(f"  Expected: 63796b65 (cyek)")
print(f"  Match: {magic.hex() == '63796b65'}")
print()

# Code Certificate
print("CODE CERTIFICATE v1:")
print("-"*80)
code_cert = open(f'{base_path}\\code_cert_v1.bin', 'rb').read()
print(f"Size: {len(code_cert)} bytes")

magic = code_cert[0:4]
print(f"Magic: {magic.hex()} = {''.join(chr(b) for b in magic if 32 <= b < 127)}")
print(f"  Expected: 63646f63 (cdoc)")
print(f"  Match: {magic.hex() == '63646f63'}")
print()

# Image Size
image_size = struct.unpack('<I', code_cert[20:24])[0]
print(f"Image Size: 0x{image_size:08X} = {image_size} bytes = {image_size/1024:.2f} KB")
print(f"  Expected: 0x00030000 (192 KB) pentru combined.srec")
print(f"  Match: {image_size == 0x00030000}")
print()

# TLV1 (ECC_PUBKEY)
tlv1_offset = 36
tlv1_type_len = struct.unpack('<I', code_cert[tlv1_offset:tlv1_offset+4])[0]
tlv1_value = code_cert[tlv1_offset+4:tlv1_offset+4+64]
print(f"TLV1 (ECC_PUBKEY):")
print(f"  Type&Length: 0x{tlv1_type_len:08X}")
print(f"  Expected Renesas ref: 0x01088010 (OEM_BL_PK)")
print(f"  Match: {tlv1_type_len == 0x01088010}")
print()

# TLV2 (EXPECTED_CRC)
tlv2_offset = 36 + 4 + 64
tlv2_type_len = struct.unpack('<I', code_cert[tlv2_offset:tlv2_offset+4])[0]
tlv2_value = struct.unpack('<I', code_cert[tlv2_offset+4:tlv2_offset+8])[0]
print(f"TLV2 (EXPECTED_CRC):")
print(f"  Type&Length: 0x{tlv2_type_len:08X}")
print(f"  Value (CRC32): 0x{tlv2_value:08X}")
print(f"  Expected Type&Length: 0x40000001")
print(f"  Match: {tlv2_type_len == 0x40000001}")
print()

# KEYHASH from Key Cert
key_tlv2_offset = 40 + 64 + 4  # After header(32) + TLV_len(4) + TLV1_TypeLen(4) + TLV1_Value(64) + TLV2_TypeLen(4)
keyhash = key_cert[key_tlv2_offset:key_tlv2_offset+32]
print(f"Key Cert KEYHASH: {keyhash.hex()[:32]}...")
print()

# Verify SHA256(TLV1) == KEYHASH
tlv1_hash = hashlib.sha256(tlv1_value).digest()
print(f"SHA256(Code Cert TLV1): {tlv1_hash.hex()[:32]}...")
print(f"KEYHASH (from Key Cert): {keyhash.hex()[:32]}...")
print(f"Match: {tlv1_hash == keyhash}")
print()

print("="*80)
print("RESULT")
print("="*80)
print()

issues = []
if magic.hex() != '63646f63':
    issues.append("❌ Code Certificate magic incorrect")
if image_size != 0x00030000:
    issues.append(f"❌ Image Size incorrect: 0x{image_size:08X} (expected 0x00030000)")
if tlv1_type_len != 0x01088010:
    issues.append(f"❌ TLV1 Type&Length incorrect: 0x{tlv1_type_len:08X} (expected 0x01088010)")
if tlv1_hash != keyhash:
    issues.append("❌ SHA256(TLV1) != KEYHASH")

if issues:
    print("PROBLEMS FOUND:")
    for issue in issues:
        print(f"  {issue}")
    print()
    print("⚠️ Certificates DO NOT match the Renesas reference!")
    print("⚠️ Device is likely to report error AAAA0204!")
else:
    print("✅ Certificates are CORRECT!")
    print("✅ Matching Renesas reference (Jan_tests.zip)")
    print()
    print(f"  - TLV1 = OEM_BL_PK (0x01088010)")
    print(f"  - CRC32 = 0x{tlv2_value:08X}")
    print(f"  - Image Size = 0x{image_size:08X}")
    print(f"  - SHA256(TLV1) == KEYHASH")
    print()
    print("Ready for programming on device!")
